"""
InsuranceDocGenerator
---------------------
Automatically initiates insurance claim documentation when product spoilage
or significant financial loss is detected.

Generates:
  - Incident report (JSON)
  - Chain-of-custody summary
  - Spoilage assessment with estimated value at risk
"""

from __future__ import annotations

import json
import logging
import urllib.request
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List

from config import INSURANCE_API_URL

logger = logging.getLogger(__name__)

# TODO: Replace with a product catalogue lookup (by product_id / NDC code).
#   $25/dose and 5000 doses/container are rough order-of-magnitude placeholders.
#   Real values differ significantly: mRNA COVID-19 ~$20–$30, MMR ~$50–$70,
#   specialty biologics can exceed $500/dose.  Container capacity also varies
#   by product, packaging format, and cold-chain configuration.
VACCINE_VALUE_PER_DOSE_USD  = 25.0
DEFAULT_DOSES_PER_CONTAINER = 5000


class InsuranceDocGenerator:
    def __init__(self, api_url: str = INSURANCE_API_URL):
        self._url = api_url

    def generate(self, assessment: Any) -> Dict[str, Any]:
        """Create and submit a preliminary insurance claim document."""
        doc = self._build_claim(assessment)
        response = self._submit(doc)
        logger.info("[%s] Insurance claim %s initiated → %s",
                    assessment.shipment_id, doc["claim_id"],
                    response.get("status"))
        return {"claim_id": doc["claim_id"], "response": response, "document": doc}

    def generate_chain_of_custody(
        self,
        shipment_id: str,
        audit_records: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """
        Build chain-of-custody document from audit log records.

        TODO: Wire this up — currently not called from anywhere in the pipeline.
          Call from cascade_orchestrator when INITIATE_INSURANCE or EMERGENCY_RECALL
          is executed, pulling records via AuditLogger.get_shipment_history().
        """
        return {
            "document_type": "CHAIN_OF_CUSTODY",
            "shipment_id":   shipment_id,
            "generated_at":  datetime.now(timezone.utc).isoformat(),
            "record_count":  len(audit_records),
            "events":        [
                {
                    "timestamp":  r.get("timestamp"),
                    "event_type": r.get("event_type"),
                    "summary":    str(r.get("payload", ""))[:200],
                }
                for r in audit_records
            ],
            "regulatory_reference": "GDP §1.4 – Traceability",
        }

    # ------------------------------------------------------------------

    def _build_claim(self, assessment: Any) -> Dict[str, Any]:
        value_at_risk = (
            assessment.spoilage_prob
            * DEFAULT_DOSES_PER_CONTAINER
            * VACCINE_VALUE_PER_DOSE_USD
        )
        return {
            "claim_id":         str(uuid.uuid4()),
            "document_type":    "PRELIMINARY_INSURANCE_CLAIM",
            "shipment_id":      assessment.shipment_id,
            "container_id":     assessment.container_id,
            "incident_date":    assessment.assessed_at.isoformat(),
            "submitted_at":     datetime.now(timezone.utc).isoformat(),
            "risk_level":       assessment.risk_level.value,
            "spoilage_probability": round(assessment.spoilage_prob, 4),
            "estimated_loss_usd": round(value_at_risk, 2),
            "anomalies": [
                {
                    "type":        an.anomaly_type.value,
                    "severity":    an.severity.value,
                    "description": an.description,
                    "detected_at": an.detected_at.isoformat(),
                }
                for an in assessment.anomalies
            ],
            "justification":   assessment.justification,
            "regulatory_refs": ["GDP §9.2", "21 CFR 600.15"],
            "status":          "DRAFT",
            "notes":           (
                "Auto-generated by PharmaCargoMonitor AI system. "
                "Requires human review before formal submission."
            ),
        }

    def _submit(self, doc: Dict[str, Any]) -> Dict[str, Any]:
        try:
            data = json.dumps(doc).encode("utf-8")
            req  = urllib.request.Request(
                self._url,
                data    = data,
                headers = {"Content-Type": "application/json"},
                method  = "POST",
            )
            with urllib.request.urlopen(req, timeout=5) as resp:
                return {"status": "submitted", "http_status": resp.status}
        except Exception as exc:
            logger.warning("Insurance API unreachable (%s) — dry-run mode", exc)
            return {"status": "dry_run", "claim_id": doc["claim_id"]}
